### ISSUE TITLE
Seems glyphs dropped when edit and reload the page

### ISSUE THREAD

**Issue by c8seki** [googlei18n/TachyFont#487]
I have changed some constants to my cause.

1. Changed the url to //font.cf as I don't find where to put params on the changed js, and corresponding family name from jp to kr-web or whatever. You'll see from the following gist link :)
2. Try to change the text from HTML.
3. The refreshed page dropps some of the characters, and can't update the localDB.

Plus, I want to know how to individually add custom font-set family.

Thanks for the great work!!

Reference Gist : https://gist.github.com/c8seki/afd5c52f4a1ce4fd5a10

**Comment by bstell** [comment]
There was a problem where the new data was not loaded if there was already persisted data. This was fixed in https://github.com/googlei18n/TachyFont/commit/e025fb4c67be86a5803507a04945908c749c3518
